project:
  type: website
  output-dir: docs

website:
  title: "CDC"
  navbar:
    background: primary
    search: true
    logo: logo-cdc.png
    left:
      - href: index.qmd
        text: ACCUEIL
      - href: nous-connaitre.qmd
        text: CDC
      - href: contacts.qmd
        text: CONTACTS
      - href: inscription.qmd
        text: INSCRIPTION
    right: 
      - icon: facebook
        href: https://www.facebook.com/cerclechercheurs
        aria-label: Quarto Facebook
      - icon: linkedin
        href: https://www.linkedin.com/in/association-cercle-des-chercheurs-25b5aa237/
        aria-label: Quarto Linkedin
  page-footer:
   left: Copyright Â© 2022 Cercle Des Chercheurs, Association.
   right: 
    - icon: github
      href: https://github.com/oousmane/cdc-website
      aria-label: Quarto Github
format:
  html:
    theme: "sandstone"
    css: styles.css
    toc: true
license: CC BY-NC
editor: visual

